carts/urls.py
from mystore import views
from django.urls import path
from .import views

urlpatterns =[
    path('', views.cart, name ='cart'),
    path('add_cart/<int:producto_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:producto_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:producto_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name= 'checkout'),
]

mystore/urls.py
from django import urls
from mystore import settings
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/',include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('seguro/', admin.site.urls),
    path('', views.home, name='home'),
    path('tienda/', include('tienda.urls')),
    path('cart/', include('carts.urls')),
    path('cuentas/', include('cuentas.urls')),

    # Orders 
    path('orders/', include('orders.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.tienda, name='tienda'),
    path('categoria/<slug:categorias_slug>/', views.tienda, name='productos_por_categorias'),
    path('categoria/<slug:categorias_slug>/<slug:productos_slug>/', views.detalles_producto, name='detalles_producto'),
    path('buscar/', views.buscar, name='buscar'),
    path('submit_review/<int:producto_id>/', views.submit_review, name='submit_review'),
]

tienda/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from categorias.models import Categoria
from django.urls import reverse
from cuentas.models import Account

from django.db.models import Avg, Count





class Producto(models.Model):

    producto         = models.CharField(max_length=200, unique=True)
    slug             = models.SlugField(max_length=200, unique=True)
    descripcion      = models.TextField(max_length=500, blank= True)
    precio           = models.IntegerField()
    images           = models.ImageField(upload_to ='photos/products')
    stock            = models.IntegerField()
    esta_disponible  = models.BooleanField(default=True)
    categoria        = models.ForeignKey(Categoria, on_delete= models.CASCADE)
    fecha_creada     = models.DateTimeField(auto_now_add=True)
    fecha_modificada = models.DateTimeField(auto_now=True)

    def get_url (self):
        return reverse('detalles_producto', args=[self.categoria.slug, self.slug])

    def __str__(self):
        return self.producto

    def averageRating(self):
        reviews = ReviewRating.objects.filter(producto=self, status = True).aggregate(average = Avg('rating'))
        avg = 0
        if reviews['average']is not None:
            avg = float(reviews['average'])
        return avg

    def countReview(self):
        reviews = ReviewRating.objects.filter(producto=self, status = True).aggregate(count = Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count




class ManagerVariacion(models.Manager):
    def colors(self):
        return super(ManagerVariacion, self).filter(categoria_variacion='color', esta_activo=True)

    def sizes(self):
        return super(ManagerVariacion, self).filter(categoria_variacion='size', esta_activo = True)



escoger_variacion_categoria = (
    ('color', 'color'),
    ('size', 'size'),
)


class Variaciones(models.Model):
    producto            = models.ForeignKey(Producto, on_delete=models.CASCADE)
    categoria_variacion = models.CharField(max_length=100, choices= escoger_variacion_categoria)
    valor_variacion     = models.CharField(max_length=100)
    esta_activo         = models.BooleanField(default=True)
    fecha_creado        = models.DateTimeField(auto_now_add=True)

    objects = ManagerVariacion()

    def __str__(self):
        return self.valor_variacion




class ReviewRating(models.Model):
    producto     = models.ForeignKey(Producto, on_delete=models.CASCADE)
    user         = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject      = models.CharField(max_length=100, blank=True)
    review       = models.TextField(max_length=500, blank=True)
    rating       = models.FloatField()
    ip           = models.CharField(max_length=20, blank=True)
    status       = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_at   = models.DateTimeField(auto_now=True)

    def __str__ (self):
        return self.subject 


class ProductGallery(models.Model):
    producto = models.ForeignKey(Producto, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to ='photos/products', max_length =255)

    def __str__(self):
        return self.producto.producto

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

   

tienda/forms.py
from django import forms
from .models import ReviewRating

class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'rating', 'review']

carts/views.py
from django.shortcuts import  render, redirect, get_object_or_404
from tienda.models import Producto, Variaciones
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, producto_id):
    current_user = request.user
    producto = Producto.objects.get(id= producto_id) #get the producto id
    #if user is authenticated

    if current_user.is_authenticated:
        variaciones_producto = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variacion = Variaciones.objects.get(producto=producto, categoria_variacion__iexact= key, valor_variacion__iexact = value)
                    variaciones_producto.append(variacion)
                except:
                    pass
    
        
        is_cart_item_exists = CartItem.objects.filter(producto = producto, user=current_user).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(producto=producto, user= current_user)
            ex_var_list = []
            id = []
            for item in cart_item :
                variaciones_existentes = item.variaciones.all()
                ex_var_list.append(list(variaciones_existentes))
                id.append(item.id)

        

            if variaciones_producto in ex_var_list:
                #increase cart item quantity
                index = ex_var_list.index(variaciones_producto)
                item_id = id[index]
                item = CartItem.objects.get(producto= producto, id=item_id)
                item.quantity += 1
                item.save()

            else:
               
                item = CartItem.objects.create(producto= producto, quantity = 1, user= current_user)
                if len(variaciones_producto)> 0:
                    item.variaciones.clear()
                    item.variaciones.add(*variaciones_producto)
                item.save()
               
        else:  
        
            cart_item = CartItem.objects.create(
                producto = producto,
                quantity = 1,
                user = current_user,

            )
        
            if len(variaciones_producto)> 0:
                cart_item.variaciones.clear()
                cart_item.variaciones.add(*variaciones_producto)
            cart_item.save()
    
        return redirect('cart')
    else:
    #if the user is not authenticated

        variaciones_producto = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variacion = Variaciones.objects.get(producto=producto, categoria_variacion__iexact= key, valor_variacion__iexact = value)
                    variaciones_producto.append(variacion)
                except:
                    pass
    
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))  #get the cartI present in the session
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id = _cart_id(request)
            )
        cart.save()

        is_cart_item_exists = CartItem.objects.filter(producto = producto, cart = cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(producto=producto, cart=cart)
            # existing_variations -> database
            # current variations -> variaciones_producto
            # item =_id -> database

            ex_var_list = []
            id = []
            for item in cart_item :
                variaciones_existentes = item.variaciones.all()
                ex_var_list.append(list(variaciones_existentes))
                id.append(item.id)

        

            if variaciones_producto in ex_var_list:
                # increase cart item quantity
                index = ex_var_list.index(variaciones_producto)
                item_id = id[index]
                item = CartItem.objects.get(producto= producto, id=item_id)
                item.quantity += 1
                item.save()

            else:
                item = CartItem.objects.create(producto= producto, quantity = 1, cart = cart)
                if len(variaciones_producto)> 0:
                    item.variaciones.clear()
                    item.variaciones.add(*variaciones_producto)
                item.save()
        else:  
            cart_item = CartItem.objects.create(
                producto = producto,
                quantity = 1,
                cart = cart,
            )
        
            if len(variaciones_producto)> 0:
                cart_item.variaciones.clear()
                cart_item.variaciones.add(*variaciones_producto)
            cart_item.save()
    
        return redirect('cart')


def remove_cart(request, producto_id, cart_item_id ):
    
    producto = get_object_or_404(Producto, id = producto_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(producto= producto, user= request.user, id= cart_item_id)
        else:
            cart = Cart.objects.get(cart_id= _cart_id(request))
            cart_item = CartItem.objects.get(producto=producto, cart=cart, id= cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect ('cart')



def remove_cart_item(request, producto_id, cart_item_id):

    producto = get_object_or_404(Producto, id = producto_id)
    
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(producto= producto, user= request.user, id=cart_item_id)

    else:
        cart = Cart.objects.get(cart_id= _cart_id(request))
        cart_item = CartItem.objects.get(producto= producto, cart = cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart')

def cart(request, total=0, quantity=0, cart_item=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items =  CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id= _cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active= True)
        for cart_item in cart_items:
            total += (cart_item.producto.precio * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (7 * total)/100
        grand_total= total + tax 
    except ObjectDoesNotExist:
        pass #  just ignore

    context = {
             'total': total,
             'quantity': quantity,
             'cart_items': cart_items,
             'tax': tax,
             'grand_total': grand_total,

         }


    return render(request, 'tienda/cart.html', context)

@login_required(login_url='entrar')
def checkout(request,total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total=0
        if request.user.is_authenticated:
            cart_items =  CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id= _cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active= True)
        for cart_item in cart_items:
            total += (cart_item.producto.precio * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (7 * total)/100
        grand_total= total + tax 
    except ObjectDoesNotExist:
        pass # just ignore

    context = {
             'total': total,
             'quantity': quantity,
             'cart_items': cart_items,
             'tax': tax,
             'grand_total': grand_total,

         }
    return render (request,'tienda/checkout.html', context)
      

tienda/views.py
from django.contrib import messages
from .forms import ReviewForm
from django.http.response import HttpResponse
from django.shortcuts import redirect, render,  get_object_or_404
from .models import ProductGallery, Producto, ReviewRating
from categorias.models import Categoria
from carts.models import CartItem
from carts.views import _cart_id
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse
from django.db.models import Q
from orders.models import OrderProduct



def tienda(request, categorias_slug=None):
    categorias = None
    productos = None

    if categorias_slug != None:
        categorias = get_object_or_404(Categoria, slug = categorias_slug)
        productos = Producto.objects.filter(categoria= categorias, esta_disponible= True)
        paginator = Paginator(productos, 1)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        contar_producto = productos.count()
    else:
        productos = Producto.objects.all().filter(esta_disponible=True).order_by('id')
        paginator = Paginator(productos, 3)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        contar_producto = productos.count()

    context = {
        'productos': paged_products,
        'contar_producto': contar_producto,
    }
    return render(request, 'tienda/tienda.html', context)



def detalles_producto(request, categorias_slug, productos_slug):
    try:
        solo_producto = Producto.objects.get(categoria__slug = categorias_slug, slug=productos_slug)
        en_carrito = CartItem.objects.filter(cart__cart_id= _cart_id(request), producto = solo_producto).exists()
       
    except Exception as e:
        raise e

    if request.user.is_authenticated:
        try:
            orderproducto = OrderProduct.objects.filter(user= request.user, producto_id= solo_producto.id).exists()
        except OrderProduct.DoesNotExist:
            orderproducto = None
    else:
        orderproducto = None

    # Get reviews ratings
    reviews = ReviewRating.objects.filter(producto_id= solo_producto.id, status = True)

    # Get Product Gallery
    product_gallery = ProductGallery.objects.filter(producto_id= solo_producto.id)

    context = {
        'solo_producto': solo_producto,
        'en_carrito'   : en_carrito,
        'orderproducto': orderproducto,
        'reviews': reviews,
        'product_gallery': product_gallery,
    }
    return render(request, 'tienda/detalles_producto.html', context)



def buscar(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            productos = Producto.objects.order_by('-fecha_creada').filter(Q(descripcion__icontains=keyword) | Q(producto__icontains=keyword))
            contar_producto = productos.count()
            
    context = {
        'productos': productos,
        'contar_producto': contar_producto,
    }    
    return render(request, 'tienda/tienda.html', context)


def submit_review(request, producto_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id, producto__id=producto_id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Gracias! Su revicion ha sido actualizada.')
            return redirect(url)
        
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.producto_id = producto_id
                data.user_id= request.user.id
                data.save()
                messages.success(request, 'Gracias! Su revicion ha sido sometida.')
                return redirect(url)


#

templates/tienda/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    {% if not cart_items %}
        <h2 class="text-center">El carrito esta vacio</h2>
        <br>
       <div class="text-center">
        <a href="{% url 'tienda' %}" class="btn btn-primary">Continuar Comprando</a>
       </div>

    {% else %}

    
    <div class="row">
        <aside class="col-lg-9">
    <div class="card">
    <table class="table table-borderless table-shopping-cart">
    <thead class="text-muted">
    <tr class="small text-uppercase">
      <th scope="col">Product</th>
      <th scope="col" width="120">Quantity</th>
      <th scope="col" width="120">Price</th>
      <th scope="col" class="text-right" width="200"> </th>
    </tr>
    </thead>
    <tbody>
    
    {%  for cart_item in cart_items %}
    <tr>
        <td>
            <figure class="itemside align-items-center">
                <div class="aside"><img src="{{ cart_item.producto.images.url }}" class="img-sm"></div>
                <figcaption class="info">
                    <a href="{{cart_item.producto.get_url }}" class="title text-dark">{{ cart_item.producto.producto }}</a>
                    <p class="text-muted small">
                        {% if cart_item.variaciones.all %}
                            {% for item in cart_item.variaciones.all %}
                                 {{ item.categoria_variacion | capfirst }} : {{ item.valor_variacion | capfirst }} <br>
                            {% endfor %}
                        {% endif %}
                    </p>
                </figcaption>
            </figure>
        </td>
        <td> 
            <!-- col.// -->
                        <div class="col"> 
                            <div class="input-group input-spinner">
                                <div class="input-group-prepend">
                                <a href="{% url 'remove_cart' cart_item.producto.id cart_item.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
                                </div>
                                <input type="text" class="form-control"  value="{{ cart_item.quantity }}">
                                <div class="input-group-append">
                                    <form action="{% url 'add_cart' cart_item.producto.id %}" method="POST">
                                        {% csrf_token %}
                                        {% for item in cart_item.variaciones.all %}
                                        <input type="hidden" name= "{{ item.categoria_variacion }}" value = "{{ item.valor_variacion | capfirst }}" >
                                        {% endfor%}
                                        <button class="btn btn-light"type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
                                    </form>
                                </div>

                            </div> <!-- input-group.// -->
                        </div> <!-- col.// -->
        </td>
        <td> 
            <div class="price-wrap"> 
                <var class="price"> $ {{ cart_item.sub_total }}</var> 
                <small  class="text-muted"> $ {{ cart_item.producto.precio }} </small>  
            </div> <!-- price-wrap .// -->
        </td>
        <td class="text-right"> 
        <a href="{% url 'remove_cart_item' cart_item.producto.id cart_item.id %}"onclick="return confirm( 'Esta seguro que desea removerlo')" class="btn btn-danger"> Remove</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <aside class="col-lg-3">
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total Price:</dt>
                  <dd class="text-right">$ {{ total }}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Tax:</dt>
                  <dd class="text-right"> $ {{ tax }}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Grand Total:</dt>
                  <dd class="text-right text-dark b"><strong>$ {{ grand_total }}</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="{% static 'images/misc/payments.png' %}" height="26">
                   
                </p>
                <a href="{% url 'checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
                <a href="{% url 'tienda' %}" class="btn btn-light btn-block">Continue Shopping</a>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
    {% endif %}
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock%}

templates/tienda/detalles_producto.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<section class="section-content padding-y bg">
	<div class="container">
	
	<!-- ============================ COMPONENT 1 ================================= -->
	<div class="card">
		<div class="row no-gutters">
			<aside class="col-md-6">
	<article class="gallery-wrap"> 
		<div class="img-big-wrap mainImage">
		 <center><img src="{{ solo_producto.images.url }}"></center>
		</div> <!-- img-big-wrap.// -->
		
	</article> <!-- gallery-wrap .end// -->
	<ul class="thumb">
		<li>
			<a href="{{ solo_producto.images.url }}" target="mainImage"><img src="{{ solo_producto.images.url }}" alt="Imagen Producto"></a>
			{% for i in product_gallery %}
			<a href="{{ i.image.url}}" target="mainImage"><img src="{{i.image.url}}"alt="Imagen Producto"></a>
			{% endfor %}
		</li>
	</ul>
			</aside>
			<main class="col-md-6 border-left">

	    <form action="{% url 'add_cart' solo_producto.id %}" method="POST">
			{% csrf_token %}
			<article class="content-body">
			
			<h2 class="title">{{ solo_producto.producto }}</h2>
			<div class="rating-star">
				<span>
					<i class="fa fa-star{% if solo_producto.averageRating < 0.5 %}-o{% elif solo_producto.averageRating >= 0.5 and solo_producto.averageRating < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if solo_producto.averageRating < 1.5 %}-o{% elif solo_producto.averageRating >= 1.5 and solo_producto.averageRating < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if solo_producto.averageRating < 2.5 %}-o{% elif solo_producto.averageRating >= 2.5 and solo_producto.averageRating < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if solo_producto.averageRating < 3.5 %}-o{% elif solo_producto.averageRating >= 3.5 and solo_producto.averageRating < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if solo_producto.averageRating < 4.5 %}-o{% elif solo_producto.averageRating >= 4.5 and solo_producto.averageRating < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
					<span>{{ solo_producto.countReview }} Reviciones</span>
				</span>
			</div>
			
			
			<div class="mb-3"> 
				<var class="price h4">${{ solo_producto.precio }}</var> 
			</div> 
			

			<p>{{ solo_producto.descripcion }}</p>
			
			
			<hr>
				<div class="row">
					<div class="item-option-select">
						<h6>Seleccionar Color</h6>
						<select name="color"  class="form-control" required>
							<option value="" disable selected>Selecionar</option>
							{% for i in solo_producto.variaciones_set.colors %}
							<option value="{{ i.valor_variacion | lower }}">{{ i.valor_variacion | capfirst}}</option>
							{% endfor %}
						</select>
					</div>
				</div> <!-- row.// -->

				<div class="row">
					<div class="item-option-select">
						<h6>Seleccionar Talla</h6>
						<select name="size"  class="form-control">
							<option value="" disable selected>Selecionar</option>
							{% for i in solo_producto.variaciones_set.sizes %}
							<option value="{{ i.valor_variacion | lower }}">{{ i.valor_variacion | capfirst }}</option>
							{% endfor %}
						</select>
					</div>
				</div> <!-- row.// -->
			<hr>
				
				{% if solo_producto.stock <= 0 %}
					<h5 class ="text-danger">Producto Agotado</h5>
				{% else %}
				<button type="submit" class="btn  btn-primary"> <span class="text">Agregar al Carrito</span> <i class="fas fa-shopping-cart"></i>  </button>
				{% endif %}
			</article> <!-- product-info-aside .// -->
	    </form>
			</main> <!-- col.// -->
		</div> <!-- row.// -->
	</div> <!-- card.// -->
	<!-- ============================ COMPONENT 1 END .// ================================= -->
	
	<br>
	
	<div class="row">
				<div class="col-md-9">
	
		

		<form action="{% url 'submit_review' solo_producto.id %}" method = "POST">
			{% csrf_token %}
			<h5>Escriba su Revision</h5>
			
			<div>

				<label> Como usted cataloga este producto ?</label>
				<br>
				<div class="rate">
					<input type="radio" name="rating" id="rating10" value="5"required><label for= "rating10" title="5"></label>
					<input type="radio" name="rating" id="rating9" value="4.5"required><label for= "rating9" title="4.5" class="half"></label>
					<input type="radio" name="rating" id="rating8" value="4"required><label for= "rating8" title="4"></label>
					<input type="radio" name="rating" id="rating7" value="3.5"required><label for= "rating7" title="3.5" class="half"></label>
					<input type="radio" name="rating" id="rating6" value="3"required><label for= "rating6" title="3"></label>
					<input type="radio" name="rating" id="rating5" value="2.5"required><label for= "rating5" title="2.5" class="half"></label>
					<input type="radio" name="rating" id="rating4" value="2"required><label for= "rating4" title="2"></label>
					<input type="radio" name="rating" id="rating3" value="1.5"required><label for= "rating3" title="1.5" class="half"></label>
					<input type="radio" name="rating" id="rating2" value="1"required><label for= "rating2" title="1"></label>
					<input type="radio" name="rating" id="rating1" value="0.5"required><label for= "rating1" title="0.5" class="half"></label>
				</div>
		<br>

		

				Review Title:
				<input type="text" class="form-control" name="subject">
				<br>
				Review:
				<textarea name="review" rows="4" class="form-control"></textarea>
				<br>
				{% if user.is_authenticated %}
					{% if orderproducto %}
						<input type="submit" value="Submit Review"class="btn btn-primary">
					{% else %}	
						<p>Usted debe comprar este producto para hacer una revicion.</p>
					{% endif%}
				{% else %}
						<p>Usted debe entrar a su cuenta para hacer una revicion.<span><a href="{% url 'entrar' %}"> Entrar Aqui</a></span></p>
				{% endif %}
			</div>
		<br>
		{% include 'includes/alerts.html' %}
		</form>
		<br>
		<header class="section-heading">
			<h3>Reviciones de Clientes </h3>
			<div class="rating-star">
				<span>
					<i class="fa fa-star{% if solo_producto.averageRating < 0.5 %}-o{% elif solo_producto.averageRating >= 0.5 and solo_producto.averageRating < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if solo_producto.averageRating < 1.5 %}-o{% elif solo_producto.averageRating >= 1.5 and solo_producto.averageRating < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if solo_producto.averageRating < 2.5 %}-o{% elif solo_producto.averageRating >= 2.5 and solo_producto.averageRating < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if solo_producto.averageRating < 3.5 %}-o{% elif solo_producto.averageRating >= 3.5 and solo_producto.averageRating < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if solo_producto.averageRating < 4.5 %}-o{% elif solo_producto.averageRating >= 4.5 and solo_producto.averageRating < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
					<span>{{ solo_producto.countReview }} Reviciones</span>
				</span>
			</div>
			
		</header>

		{% for review in reviews %}
	
		<article class="box mb-3">
			<div class="icontext w-100">
				
				<div class="text">
					<span class="date text-muted float-md-right">{{ review.updated_at }} </span>  
					<h6 class="mb-1">{{ review.user.full_name }} </h6>
					<div class="rating-star">
						<span>
							<i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
							<i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
							<i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
							<i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
							<i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
						</span>

					</div>
					<div class="rating-star">
						<span>
						
							
							
						</span>
					</div>
					
				</div>
			</div> <!-- icontext.// -->
			<div class="mt-3">
				<h6>{{ review.subject }}</h6>
				<p>
					{{review.review}}
				</p>	
			</div>
		</article>
		{% endfor %}
	
		
	
		</div> <!-- col.// -->
	</div> <!-- row.// -->
	
	
	</div> <!-- container .//  -->
	</section>
	<!-- ========================= SECTION CONTENT END// ========================= -->
	

{% endblock %}